module.exports = {
  type1_national_teams: [
    { country: "Tunisia", iso2: "tn", url: "https://en.wikipedia.org/wiki/Tunisia_national_football_team" },
    { country: "Morocco", iso2: "ma", url: "https://en.wikipedia.org/wiki/Morocco_national_football_team" },
    { country: "Algeria", iso2: "dz", url: "https://en.wikipedia.org/wiki/Algeria_national_football_team" },
    { country: "Senegal", iso2: "sn", url: "https://en.wikipedia.org/wiki/Senegal_national_football_team" },
    { country: "Nigeria", iso2: "ng", url: "https://en.wikipedia.org/wiki/Nigeria_national_football_team" },
    { country: "Egypt", iso2: "eg", url: "https://en.wikipedia.org/wiki/Egypt_national_football_team" },
    { country: "Ghana", iso2: "gh", url: "https://en.wikipedia.org/wiki/Ghana_national_football_team" },
    { country: "Ivory Coast", iso2: "ci", url: "https://en.wikipedia.org/wiki/Ivory_Coast_national_football_team" },
    { country: "Cameroon", iso2: "cm", url: "https://en.wikipedia.org/wiki/Cameroon_national_football_team" },
    { country: "Mali", iso2: "ml", url: "https://en.wikipedia.org/wiki/Mali_national_football_team" },
    { country: "Brazil", iso2: "br", url: "https://en.wikipedia.org/wiki/Brazil_national_football_team" },
    { country: "Argentina", iso2: "ar", url: "https://en.wikipedia.org/wiki/Argentina_national_football_team" },
    { country: "France", iso2: "fr", url: "https://en.wikipedia.org/wiki/France_national_football_team" },
    { country: "Portugal", iso2: "pt", url: "https://en.wikipedia.org/wiki/Portugal_national_football_team" },
    { country: "Spain", iso2: "es", url: "https://en.wikipedia.org/wiki/Spain_national_football_team" },
    { country: "Germany", iso2: "de", url: "https://en.wikipedia.org/wiki/Germany_national_football_team" },
    { country: "Japan", iso2: "jp", url: "https://en.wikipedia.org/wiki/Japan_national_football_team" },
    { country: "South Korea", iso2: "kr", url: "https://en.wikipedia.org/wiki/South_Korea_national_football_team" },
    { country: "Saudi Arabia", iso2: "sa", url: "https://en.wikipedia.org/wiki/Saudi_Arabia_national_football_team" },
    { country: "United States", iso2: "us", url: "https://en.wikipedia.org/wiki/United_States_men%27s_national_soccer_team" }
  ],
  type2_international_lists: [
    "https://en.wikipedia.org/wiki/List_of_Tunisia_international_footballers",
    "https://en.wikipedia.org/wiki/List_of_Morocco_international_footballers",
    "https://en.wikipedia.org/wiki/List_of_Algeria_international_footballers",
    "https://en.wikipedia.org/wiki/List_of_Senegal_international_footballers",
    "https://en.wikipedia.org/wiki/List_of_Nigeria_international_footballers",
    "https://en.wikipedia.org/wiki/List_of_Egypt_international_footballers",
    "https://en.wikipedia.org/wiki/List_of_Ghana_international_footballers",
    "https://en.wikipedia.org/wiki/List_of_Brazil_international_footballers",
    "https://en.wikipedia.org/wiki/List_of_France_international_footballers",
    "https://en.wikipedia.org/wiki/List_of_Argentina_international_footballers",
    "https://en.wikipedia.org/wiki/List_of_Portugal_international_footballers",
    "https://en.wikipedia.org/wiki/List_of_Japan_international_footballers"
  ],
  type3_categories: [
    "https://en.wikipedia.org/wiki/Category:Tunisian_footballers",
    "https://en.wikipedia.org/wiki/Category:Moroccan_footballers",
    "https://en.wikipedia.org/wiki/Category:Algerian_footballers",
    "https://en.wikipedia.org/wiki/Category:Senegalese_footballers",
    "https://en.wikipedia.org/wiki/Category:Nigerian_footballers",
    "https://en.wikipedia.org/wiki/Category:Egyptian_footballers",
    "https://en.wikipedia.org/wiki/Category:Ghanaian_footballers",
    "https://en.wikipedia.org/wiki/Category:Ivorian_footballers",
    "https://en.wikipedia.org/wiki/Category:Cameroonian_footballers",
    "https://en.wikipedia.org/wiki/Category:Malian_footballers",
    "https://en.wikipedia.org/wiki/Category:Brazilian_footballers",
    "https://en.wikipedia.org/wiki/Category:Argentine_footballers",
    "https://en.wikipedia.org/wiki/Category:French_footballers",
    "https://en.wikipedia.org/wiki/Category:Portuguese_footballers",
    "https://en.wikipedia.org/wiki/Category:Spanish_footballers",
    "https://en.wikipedia.org/wiki/Category:German_footballers",
    "https://en.wikipedia.org/wiki/Category:Japanese_footballers",
    "https://en.wikipedia.org/wiki/Category:South_Korean_footballers",
    "https://en.wikipedia.org/wiki/Category:Saudi_Arabian_footballers"
  ],
  type5_fbref: [
    "https://fbref.com/en/country/players/TUN/Tunisia-Football-Players",
    "https://fbref.com/en/country/players/MAR/Morocco-Football-Players",
    "https://fbref.com/en/country/players/ALG/Algeria-Football-Players",
    "https://fbref.com/en/country/players/SEN/Senegal-Football-Players",
    "https://fbref.com/en/country/players/NGA/Nigeria-Football-Players",
    "https://fbref.com/en/country/players/EGY/Egypt-Football-Players",
    "https://fbref.com/en/country/players/BRA/Brazil-Football-Players",
    "https://fbref.com/en/country/players/ARG/Argentina-Football-Players",
    "https://fbref.com/en/country/players/FRA/France-Football-Players",
    "https://fbref.com/en/country/players/POR/Portugal-Football-Players",
    "https://fbref.com/en/country/players/ESP/Spain-Football-Players",
    "https://fbref.com/en/country/players/GER/Germany-Football-Players",
    "https://fbref.com/en/country/players/JPN/Japan-Football-Players",
    "https://fbref.com/en/country/players/KOR/Korea-Republic-Football-Players",
    "https://fbref.com/en/country/players/CMR/Cameroon-Football-Players",
    "https://fbref.com/en/country/players/CIV/Cote-dIvoire-Football-Players",
    "https://fbref.com/en/country/players/GHA/Ghana-Football-Players"
  ]
};
