ALTER TABLE public.players
ADD COLUMN IF NOT EXISTS id UUID DEFAULT gen_random_uuid(),
ADD COLUMN IF NOT EXISTS name TEXT,
ADD COLUMN IF NOT EXISTS nationality TEXT,
ADD COLUMN IF NOT EXISTS nationality_code TEXT,
ADD COLUMN IF NOT EXISTS club TEXT,
ADD COLUMN IF NOT EXISTS current_club TEXT,
ADD COLUMN IF NOT EXISTS position TEXT,
ADD COLUMN IF NOT EXISTS dob DATE,
ADD COLUMN IF NOT EXISTS date_of_birth DATE,
ADD COLUMN IF NOT EXISTS transfermarkt_id TEXT,
ADD COLUMN IF NOT EXISTS image_url TEXT,
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS player_status TEXT DEFAULT 'active',
ADD COLUMN IF NOT EXISTS last_season INT,
ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS data_sources TEXT[],
ADD COLUMN IF NOT EXISTS goals_2025 INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS assists_2025 INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS matches_2025 INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS rating_2025 FLOAT DEFAULT 0,
ADD COLUMN IF NOT EXISTS form_score FLOAT DEFAULT 0,
ADD COLUMN IF NOT EXISTS market_value BIGINT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_players_nationality ON public.players (nationality);
CREATE UNIQUE INDEX IF NOT EXISTS uq_players_transfermarkt_id ON public.players (transfermarkt_id);
